package com.zachary.BI.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.util.Date;

@Data
@TableName("upload_session")
public class UploadSession {

    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /**
     * Public UUID used by the frontend. Do not expose id instead.
     */
    private String uploadId;

    /**
     * Owner checked on every upload, status, complete, and abort request.
     */
    private Long userId;

    /**
     * Metadata only; never use this as a server filesystem path.
     */
    private String originalFileName;

    private String sourceFileType;
    private String contentType;
    private Long totalSize;
    private Integer chunkSize;
    private Integer totalChunks;

    /**
     * UUID-style internal folder name, generated by the server.
     */
    private String storageKey;

    /**
     * created / uploading / completed / expired / aborted
     */
    private String status;

    private Date expiresAt;
    private Date completedAt;
    private Date createTime;
    private Date updateTime;

    /**
     * Relative path of the final merged file. Never expose this path to clients.
     */
    private String completedStorageKey;

    /**
     * SHA-256 checksum of the completed file.
     */
    private String wholeFileSha256;

    /**
     * Identifies the server attempt that owns completion.
     */
    private String completionClaimId;

    /**
     * Used to recover a completion attempt abandoned by a crashed process.
     */
    private Date completionStartedAt;
}